
services:
  source_postgres:
    image: postgres:latest
    ports:
      - "5433:5432"
    networks:
      - elt_network
    environment:
      - POSTGRES_DB=source_db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=1724
    volumes:
      - ./source_db_init/init.sql:/docker-entrypoint-initdb.d/init.sql
  
  destination_postgres:
    image: postgres:latest
    ports:
      - "5434:5432"
    networks:
      - elt_network
    environment:
      - POSTGRES_DB=destination_db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=1724

  etl_script:
    build:
      context: /Users/guycarelarakaza/Documents/GitHub/ETL/elt/
      dockerfile: Dockerfile
    command: ["python", "etl_script.py"]
    networks:
      - elt_network
    depends_on:
      - source_postgres
      - destination_postgres

  dbt:
    build:
      context: .
      dockerfile:  Dockerfile.dbt
    command: >
      bash -c "
        echo '⏳ Waiting for destination_postgres to be ready...' &&
        until pg_isready -h destination_postgres -U root; do sleep 2; done &&
        echo '✅ Database ready, running dbt...' &&
        dbt run --profiles-dir /root/.dbt --project-dir /usr/app/postgres_etl_dbt
      "
    networks:
      - elt_network
    volumes:
      - ./postgres_etl_dbt:/usr/app/postgres_etl_dbt
      - ~/.dbt:/root/.dbt

    depends_on:
      - etl_script

    environment:
      DBT_PROFILE: default
      DBT_TARGET: dev
    
networks:
  elt_network:
    driver: bridge
